export const BOLD = 'Quicksand-Bold'
export const LIGHT = 'Quicksand-Light'
export const MEDIUM = 'Quicksand-Medium'
export const REGULAR = 'Quicksand-Regular'
export const SEMIBOLD = 'Quicksand-SemiBold'